[project]
name = "aare-oraku-forecast"
version = "0.2.2"
description = "Forecast service to fetch external data and persist forecasts to a DB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aare-logging",
    "aare-timescale",
    "configargparse>=1.7.1",
    "httpx>=0.28.1",
    "uvloop>=0.21.0",
]

[project.optional-dependencies]
gpu-auto = ["aare-shared[gpu-auto]"]
gpu = ["aare-shared[gpu]"]
cpu = ["aare-shared[cpu]"]

[tool.uv]
conflicts = [[{ extra = "gpu-auto" }, { extra = "gpu" }, { extra = "cpu" }]]

[tool.uv.sources]
aare-shared = { workspace = true }
aare-logging = { workspace = true }
aare-timescale = { workspace = true }
