logging-level: DEBUG
connection-string: "host=127.0.0.1 dbname=aare_oraku user=postgres password=password"
fields: [ "hydro/flow:first_1h@thun", "hydro/temperature:first_1h@thun", "hydro/flow:first_1h@bern", "hydro/temperature:first_1h@bern", "smn/tt:first_1h@bern", "smn/ss:sum_1h@bern" ]
