stages:
  fit-scaler:
    cmd: python scripts/fit_scaler.py
    params:
      - split.train_split
      - split.val_split
    outs:
    - data/scaler.pkl
  establish-baselines:
    cmd: python scripts/establish_baselines.py
    params:
      - general.forecast_horizon
      - split.val_split
      - split.test_split
      - validation.stride
      - validation.lookback_hours
    outs:
      - data/last_forecasts/LOCF.pkl
      - data/last_forecasts/SNAIVE.pkl
      - data/last_forecasts/MEAN.pkl
    metrics:
      - data/metrics/LOCF.json
      - data/metrics/SNAIVE.json
      - data/metrics/MEAN.json
