# values from EDA
general:
  frequency: 1h
  forecast_horizon: 96
cleanup:
  low_cutoff: 2.5
  high_cutoff: 25
  diff_threshold: 0.6  # 0.995 quantile
interpolate:
  # depending on how good imputation is,
  # could lower these a bit.
  # They work often, but sometimes fail badly.
  linear_gap_bound: 3
  cubic_gap_bound: 25
split:
  # 15 years training (9 of them clean)
  train_split: "2001-06-28"
  # 4 years validation (3 of them very clean)
  val_split: "2017-01-01"
  # 4+ years test (4 of them clean)
  test_split: "2021-01-01"
validation:
  stride: 24  # one eval per day
  # how many previous hours should AT LEAST be included when storing forecasts. will take INPUT_CHUNK_SIZE if bigger.
  min_lookback_hours: 24