# values from EDA
general:
  frequency: 1h  # this is used everywhere and integrated so tightly, that it cannot simply be changed
  forecast_horizon: 96
  timezone: "Europe/Zurich"
  # month borders of the swimming season, both sides inclusive. used for eval (and later sample weights?)
  season_start: 4  # April
  season_end: 9  # September
features:
  temp_bern:  # water temperature [°C]
    outliers:
      low_cutoff: 2.5
      high_cutoff: 25
      diff_threshold: 0.6  # 0.995 quantile
    interpolate:
      # They work often, but sometimes fail badly.
      # Could try model based imputation for larger gaps (10-50h)
      linear_gap_bound: 3
      cubic_gap_bound: 25
  flow:  # flow [m3/s]
    outliers:
      low_cutoff: 30
      high_cutoff: 99999
      diff_threshold: 14.5
    interpolate:
      linear_gap_bound: 3
      cubic_gap_bound: 23
  tt:  # air temperature [°C]
    interpolate:
      linear_gap_bound: 3
      cubic_gap_bound: 25
  ss:  # sunshine duration (minutes)
    outliers:
      low_cutoff: 0
      high_cutoff: 60
    interpolate:
      median_gap_bound: 10
  rr:  # total rainfall (mm)
    outliers:
      low_cutoff: 0
      high_cutoff: 99999
    interpolate:
      median_gap_bound: 10
  rh:  # relative humidity (%)
    outliers:
      low_cutoff: 0
      high_cutoff: 100
    interpolate:
      linear_gap_bound: 3
      cubic_gap_bound: 10
split:
  # 22 years in total (2004-2026)
  train_split: "2004-02-01"
  # 13 years training
  val_split: "2017-02-01"
  # 5 years validation
  test_split: "2022-02-01"
  # 4+ years test -> expected to eval at early 2026
validation:
  # note, anything coprime with 24 will make sure all hours are used as starts equally.
  stride: 23
  # how many previous hours should AT LEAST be included when storing forecasts. will take INPUT_CHUNK_SIZE if bigger.
  min_lookback_hours: 24
timesfm:
  version: 200m  # although 500m results in lower STD, the overall MAE is higher than 200m