[project]
name = "aare-oraku-forecast"
version = "0.4.1"
description = "Forecast service to fetch external data and persist forecasts to a DB"
requires-python = ">=3.12"
dependencies = [
    "aare",
    "aare-logging",
    "aare-timescale",
    "configargparse>=1.7.1",
    "httpx>=0.28.1",
    "uvloop>=0.21.0",
]

[project.optional-dependencies]
gpu-auto = ["aare-train[gpu-auto]"]
gpu = ["aare-train[gpu]"]
cpu = ["aare-train[cpu]"]

[tool.uv]
conflicts = [[{ extra = "gpu-auto" }, { extra = "gpu" }, { extra = "cpu" }]]

[tool.uv.sources]
aare = { workspace = true }
aare-train = { workspace = true }
aare-logging = { workspace = true }
aare-timescale = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "tqdm>=4.67.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/oraku_forecast"]
