[project]
name = "aare-oraku-api"
version = "0.1.0"
description = "API to get data from the forecast database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aare-logging",
    "aare-timescale",
    "fastapi>=0.116.1",
    "pandas>=2.3.2",
    "pydantic-settings>=2.10.1",
    "python-dotenv>=1.1.1",
    "uvicorn[standard]>=0.36.0",
]

[dependency-groups]
dev = ["fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.13"]

[tool.uv.sources]
aare-logging = { workspace = true }
aare-timescale = { workspace = true }
