[project]
name = "prediction-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "psycopg[binary,pool]>=3.2.10",
    "pydantic-settings>=2.10.1",
    "uvicorn[standard]>=0.36.0",
]

[dependency-groups]
dev = [
    "fastapi-cli[standard-no-fastapi-cloud-cli]>=0.0.13",
]
